ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /app/mission_ros_ws/src/visualnav-transformer-ros2/visualnav_transformer/deployment/livekit_bridge.py:58> exception=ValueError('api_key and api_secret must be set')>
Traceback (most recent call last):
  File "/app/mission_ros_ws/src/visualnav-transformer-ros2/visualnav_transformer/deployment/livekit_bridge.py", line 76, in main
    api.AccessToken()
  File "/opt/conda/envs/visnav_deployment_env/lib/python3.10/site-packages/livekit/api/access_token.py", line 116, in __init__
    raise ValueError("api_key and api_secret must be set")
ValueError: api_key and api_secret must be set
INFO:livekit:livekit_ffi::server:138:livekit_ffi::server - initializing ffi server v0.12.15
INFO:livekit:livekit_ffi::cabi:36:livekit_ffi::cabi - initializing ffi server v0.12.15
INFO:livekit:livekit_api::signal_client::signal_stream:96:livekit_api::signal_client::signal_stream - connecting to wss://satinav-b22o2lgk.livekit.cloud/rtc?sdk=python&protocol=15&auto_subscribe=1&adaptive_stream=0&version=0.21.2&access_token=...
WARNING:livekit:livekit::rtc_engine:388:livekit::rtc_engine - failed to connect: Signal(WsError(Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" }))), retrying... (1/3)
INFO:livekit:livekit_api::signal_client::signal_stream:96:livekit_api::signal_client::signal_stream - connecting to wss://satinav-b22o2lgk.livekit.cloud/rtc?sdk=python&protocol=15&auto_subscribe=1&adaptive_stream=0&version=0.21.2&access_token=...
WARNING:livekit:livekit::rtc_engine:388:livekit::rtc_engine - failed to connect: Signal(WsError(Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" }))), retrying... (2/3)
INFO:livekit:livekit_api::signal_client::signal_stream:96:livekit_api::signal_client::signal_stream - connecting to wss://satinav-b22o2lgk.livekit.cloud/rtc?sdk=python&protocol=15&auto_subscribe=1&adaptive_stream=0&version=0.21.2&access_token=...
